if [ ! -f ./config.sh ]
    then touch ./config.sh
fi
redo-ifchange config.sh config.sh.tmpl
. ./config.sh.tmpl
. ./config.sh


export PKG_CONFIG_PATH

req_nice_version=0.1.5
if ! pkg-config nice --atleast-version=$req_nice_version
    then echo "no libnice >= $req_nice_version" && exit 1
fi
PKG_CONFIG=$(pkg-config gloox nice gio-unix-2.0 --cflags --libs)
echo "#generated by compile.do" > $3
echo "g++ -MD -MF \$2.d -o \$3 \$2.cpp $CXX_FLAGS $PKG_CONFIG" >> $3
chmod +x $3
