redo-ifchange config config.tmpl
. ./config.tmpl
. ./config

req_nice_version=0.1.5
if ! pkg-config nice --atleast-version=$req_nice_version
    then echo "no libnice >= $req_nice_version" && exit 1
fi
PKG_CONFIG=$(pkg-config gloox nice --cflags --libs)
echo "#generated by compile.do" > $3
echo "g++ -MD -MF \$2.d -o \$3 \$2.cpp $CXX_FLAGS $PKG_CONFIG" >> $3
chmod +x $3
